version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  addmovies:
    build:
      context: .
      dockerfile: Dockerfile.addmovies
    depends_on:
      - fastapi

  mongo:
    image: mongo
    ports:
      - "27017:27017"
